name: Haxe CI Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  haxe-build-test:
    uses: vegardit/haxe-reusable-workflows/.github/workflows/test-with-haxe.yml@v1
    with:
      runner-os: ubuntu-latest
      haxe-version: 4.3.7
      haxe-args: test/compile.hxml
      haxe-libs: ludi-commons heaps uuid hlsdl
      test-hl: true
    steps:
      - name: Install HashLink dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev libjpeg-turbo8-dev libvorbis-dev libopenal-dev
      - name: Set LD_LIBRARY_PATH for HashLink
        run: |
          echo "LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
      - name: Debug HashLink Libraries
        run: |
          find /usr/lib /usr/local/lib -name "fmt.hdll" 2>/dev/null || echo "fmt.hdll not found"
          ls -l /usr/local/lib /usr/lib
          hl --version
      - name: Symlink fmt.hdll
        run: |
          sudo mkdir -p /usr/lib
          sudo ln -sf /usr/local/lib/fmt.hdll /usr/lib/fmt.hdll || true