name: Haxe CI Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  haxe-build-test:
    uses: vegardit/haxe-reusable-workflows/.github/workflows/test-with-haxe.yml@v1
    with:
      runner-os: ubuntu-latest
      haxe-version: 4.3.7
      haxe-args: test/compile.hxml
      haxe-libs: ludi-commons heaps uuid hlsdl
      test-hl: true
      before-tests: |
        # Install system dependencies for HashLink (fmt.hdll requires these)
        sudo apt-get update
        sudo apt-get install -y libpng-dev libjpeg-turbo8-dev libvorbis-dev libopenal-dev
        
        # Set LD_LIBRARY_PATH to ensure HashLink finds .hdll files
        echo "LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        
        # Debug: Check for fmt.hdll and HashLink version (visible in CI logs)
        find /usr/lib /usr/local/lib -name "fmt.hdll" 2>/dev/null || echo "fmt.hdll not found"
        ls -l /usr/local/lib /usr/lib || true
        hl --version || true
        
        # Symlink fmt.hdll as a fallback if path isn't sufficient
        sudo mkdir -p /usr/lib
        sudo ln -sf /usr/local/lib/fmt.hdll /usr/lib/fmt.hdll || true