name: Haxe CI Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  haxe-build-test:
    uses: vegardit/haxe-reusable-workflows/.github/workflows/test-with-haxe.yml@v1
    with:
      runner-os: ubuntu-latest
      haxe-version: 4.3.7
      haxe-args: test/compile.hxml
      haxe-libs: ludi-commons heaps uuid hlsdl
      test-hl: true
      pre-steps: |
        - name: Copy fmt.hdll to Hashlink install dir
          shell: bash
          env:
            HASHLINK_DIR: ${{ runner.temp }}/haxe/targets/hashlink
          run: cp test/fmt.hdll "$HASHLINK_DIR"